version: "3.9"

services:

  app:
    image: betulakman/pythonapp:v6
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: myapp
    deploy:
      replicas: 1
    ports: 
      - "8080:5000"
    restart:
      on-failure  
  

